// Suggested accounts
const suggestedAccounts = [
    {
        id: 1,
        nickname: 'datvilla94',
        name: '🔥Đạt Villa🔥',
        avatar: 'https://p16-sign-va.tiktokcdn.com/tos-maliva-avt-0068/f90cc529e5bacc99b1459a81ab73ca87~c5_100x100.jpeg?x-expires=1682060400&amp;x-signature=uWncMlvoFmms9kG9ErTbZpf1PYE%3D',
        bio: '✨ 1998 ✨\nVietnam 🇻🇳\nĐỪNG LẤY VIDEO CỦA TÔI ĐI SO SÁNH NỮA. XIN HÃY TÔN TRỌNG !',
        created_at: '2022-05-05 23:10:05',
        facebook_url: '',
        first_name: '',
        followers_count: 8,
        followings_count: 1,
        full_name: '',
        instagram_url: '',
        last_name: '',
        likes_count: 302.2,
        tick: true,
        twitter_url: '',
        updated_at: '2022-05-05 23:11:39',
        website_url: 'https://fullstack.edu.vn/',
        youtube_url: '',
    },
    {
        id: 2,
        nickname: 'tiger050794',
        name: 'Son Tung M-TP',
        avatar: 'https://p16-sign-sg.tiktokcdn.com/tos-alisg-avt-0068/115cca71265c94522079ac7e93a0274b~c5_300x300.webp?x-expires=1682060400&amp;x-signature=wlYicYsYGoTphX%2BlZBtyyOn4nbk%3D',
        bio: '✨ 1998 ✨\nVietnam 🇻🇳\nĐỪNG LẤY VIDEO CỦA TÔI ĐI SO SÁNH NỮA. XIN HÃY TÔN TRỌNG !',
        created_at: '2022-05-05 23:10:05',
        facebook_url: '',
        first_name: '',
        followers_count: 4,
        followings_count: 1,
        full_name: '',
        instagram_url: '',
        last_name: '',
        likes_count: 28.2,
        tick: true,
        twitter_url: '',
        updated_at: '2022-05-05 23:11:39',
        website_url: 'https://fullstack.edu.vn/',
        youtube_url: '',
    },
    {
        id: 3,
        nickname: 'cciinnn',
        name: 'CiiN',
        avatar: 'https://p16-sign-va.tiktokcdn.com/tos-useast2a-avt-0068-giso/aee057941301af2efecea5e2f7906c34~c5_100x100.jpeg?x-expires=1682056800&amp;x-signature=cSE%2F78yrXrWIwTwXocrTYaP%2BoDw%3D',
        bio: '✨ 1998 ✨\nVietnam 🇻🇳\nĐỪNG LẤY VIDEO CỦA TÔI ĐI SO SÁNH NỮA. XIN HÃY TÔN TRỌNG !',
        created_at: '2022-05-05 23:10:05',
        facebook_url: '',
        first_name: '',
        followers_count: 10.4,
        followings_count: 1,
        full_name: '',
        instagram_url: '',
        last_name: '',
        likes_count: 269.7,
        tick: true,
        twitter_url: '',
        updated_at: '2022-05-05 23:11:39',
        website_url: 'https://fullstack.edu.vn/',
        youtube_url: '',
    },
    {
        id: 4,
        nickname: 'vtv24news',
        name: 'VTV24',
        avatar: 'https://p16-sign-va.tiktokcdn.com/tos-useast2a-avt-0068-giso/ff6cfa684d7eb1c00409c4214d8ab62f~c5_100x100.jpeg?x-expires=1682056800&amp;x-signature=3RZ4ihfpzSIEXLRGgjBbPDmPB0g%3D',
        bio: '✨ 1998 ✨\nVietnam 🇻🇳\nĐỪNG LẤY VIDEO CỦA TÔI ĐI SO SÁNH NỮA. XIN HÃY TÔN TRỌNG !',
        created_at: '2022-05-05 23:10:05',
        facebook_url: '',
        first_name: '',
        followers_count: 5.9,
        followings_count: 1,
        full_name: '',
        instagram_url: '',
        last_name: '',
        likes_count: 185.5,
        tick: true,
        twitter_url: '',
        updated_at: '2022-05-05 23:11:39',
        website_url: 'https://fullstack.edu.vn/',
        youtube_url: '',
    },
    {
        id: 5,
        nickname: 'duyyy.real.channel',
        name: 'Ngô Đức Duy',
        avatar: 'https://p16-sign-sg.tiktokcdn.com/aweme/100x100/tiktok-obj/1665757201241090.jpeg?x-expires=1682060400&amp;x-signature=L5S%2FY1xfv%2FKBadOultQZrGluDLY%3D',
        bio: '✨ 1998 ✨\nVietnam 🇻🇳\nĐỪNG LẤY VIDEO CỦA TÔI ĐI SO SÁNH NỮA. XIN HÃY TÔN TRỌNG !',
        created_at: '2022-05-05 23:10:05',
        facebook_url: '',
        first_name: '',
        followers_count: 6.4,
        followings_count: 1,
        full_name: '',
        instagram_url: '',
        last_name: '',
        likes_count: 253,
        tick: true,
        twitter_url: '',
        updated_at: '2022-05-05 23:11:39',
        website_url: 'https://fullstack.edu.vn/',
        youtube_url: '',
    },
];

// Following accounts
const followingAccounts = [
    {
        id: 2,
        nickname: 'tiger050794',
        name: 'Son Tung M-TP',
        avatar: 'https://p16-sign-sg.tiktokcdn.com/tos-alisg-avt-0068/115cca71265c94522079ac7e93a0274b~c5_300x300.webp?x-expires=1682060400&amp;x-signature=wlYicYsYGoTphX%2BlZBtyyOn4nbk%3D',
        bio: '✨ 1998 ✨\nVietnam 🇻🇳\nĐỪNG LẤY VIDEO CỦA TÔI ĐI SO SÁNH NỮA. XIN HÃY TÔN TRỌNG !',
        created_at: '2022-05-05 23:10:05',
        facebook_url: '',
        first_name: '',
        followers_count: 4,
        followings_count: 1,
        full_name: '',
        instagram_url: '',
        last_name: '',
        likes_count: 28.2,
        tick: true,
        twitter_url: '',
        updated_at: '2022-05-05 23:11:39',
        website_url: 'https://fullstack.edu.vn/',
        youtube_url: '',
    },
];

const discoveries = [
    {
        icon: 'hashtag',
        title: 'suthatla',
    },
    {
        icon: 'hashtag',
        title: 'mackedoi',
    },
    {
        icon: 'hashtag',
        title: 'sansangthaydoi',
    },
    {
        icon: 'music',
        title: 'Yêu Đơn Phương Là Gì (MEE Remix) - Mee Media & h0n & BHMedia',
    },
    {
        icon: 'music',
        title: 'Về Nghe Mẹ Ru - NSND Bach Tuyet & Hứa Kim Tuyền & 14 Casper & Hoàng Dũng',
    },
    {
        icon: 'music',
        title: 'Thiên Thần Tình Yêu - RICKY STAR ạnd T.R.I',
    },
    {
        icon: 'hashtag',
        title: '7749hieuung',
    },
    {
        icon: 'hashtag',
        title: 'genzlife',
    },
    {
        icon: 'music',
        title: 'Anh Yêu Vội Thế (Mee Remix) - LaLa Trần, Mee Media',
    },
    {
        icon: 'music',
        title: 'Vui Lắm Nha (TikTok Remix 1) - Hương Ly & Jombie',
    },
];

export { suggestedAccounts, followingAccounts, discoveries };
